"""Prompt templates for LLM interactions"""

from .query_analysis import QUERY_ANALYSIS_PROMPT
from .response import RESPONSE_GENERATION_PROMPT
from .relevance import RELEVANCE_EVALUATION_PROMPT, BATCH_RELEVANCE_EVALUATION_PROMPT
from .rewrite import QUERY_REWRITE_PROMPT, STRATEGY_SELECTION_PROMPT
from .quality import QUALITY_EVALUATION_PROMPT
from .clarification import CLARIFICATION_PROMPT, REFINE_QUERY_PROMPT
from .web_integration import (
    WEB_QUERY_OPTIMIZATION_PROMPT,
    WEB_RESULT_RELEVANCE_PROMPT,
    WEB_SYNTHESIS_PROMPT,
)
from .decomposition import QUERY_DECOMPOSITION_PROMPT, SUB_ANSWER_SYNTHESIS_PROMPT

__all__ = [
    "QUERY_ANALYSIS_PROMPT",
    "RESPONSE_GENERATION_PROMPT",
    "RELEVANCE_EVALUATION_PROMPT",
    "BATCH_RELEVANCE_EVALUATION_PROMPT",
    "QUERY_REWRITE_PROMPT",
    "STRATEGY_SELECTION_PROMPT",
    "QUALITY_EVALUATION_PROMPT",
    "CLARIFICATION_PROMPT",
    "REFINE_QUERY_PROMPT",
    "WEB_QUERY_OPTIMIZATION_PROMPT",
    "WEB_RESULT_RELEVANCE_PROMPT",
    "WEB_SYNTHESIS_PROMPT",
    "QUERY_DECOMPOSITION_PROMPT",
    "SUB_ANSWER_SYNTHESIS_PROMPT",
]
